Support for SRV records
PhonePe/coredns-drove pull request #1
Opened 2024-08-06 21:21 UTC by gabber12

2024-08-08 03:43 UTC, santanusinha requested changes

2024-08-08 03:43 UTC, santanusinha commented on README.md
> +example:github.com/santanusinha/coredns
? what is this repo?

2024-08-08 03:43 UTC, santanusinha commented on cmd/coredns/example/Corefile
> +forward . 10.22.0.56
Remove phonepe specific stuff

2024-08-08 03:43 UTC, santanusinha commented on drove.go
> +	tr := &http.Transport{MaxIdleConnsPerHost: 10, TLSClientConfig: &tls.Config{InsecureSkipVerify: true}}
ideally this cert check skip should be an option

2024-08-08 03:43 UTC, santanusinha commented on drove.go
> +		Timeout:   0 * time.Second,
wdym `0` timeout?

2024-08-08 03:43 UTC, santanusinha commented on drove.go
> +			endpoint = es.Endpoint
break .. i guess?

2024-08-08 03:43 UTC, santanusinha commented on handler.go
> +
IMO you should implement ready and send ready when you've managed to connect to the leader

2024-08-08 03:43 UTC, santanusinha commented on metrics.go
> +	Help:      "Counter of requests made.",
imo we should have metrics around changes manifesting in the system. Let's say if polling blocks for some reason, this will alert us to issues

2024-08-12 08:12 UTC, gabber12 commented on drove.go
> +		Timeout:   0 * time.Second,
No timeout on client end, Individual timeouts are applied at request level

2024-08-13 03:46 UTC, santanusinha approved these changes

2024-08-13 03:46 UTC, merged